const projects = [
  {
    image: './Images/Project9.png',
    title: 'Poster',
    description: 'CANVA',
    liveLink: 'https://www.canva.com/design/DAF3QDKIqqs/9RkDPacHIY3fne0A1SrfCg/edit?utm_content=DAF3QDKIqqs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton',
  },
  {
    image: './Images/Project10.png',
    title: 'Poster',
    description: 'CANVA',
    liveLink: 'https://www.canva.com/design/DAGJsTCuMvI/BmE54FGasxH8JRxRJr4aqw/edit?utm_content=DAGJsTCuMvI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton',
  },
  {
    image: './Images/Project11.png',
    title: 'Wallpaper',
    description: 'CANVA',
    liveLink: 'https://www.canva.com/design/DAF8OMuf-vc/vhHUYt0Zl2f4-Tu5XwKtmg/edit?utm_content=DAF8OMuf-vc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton',
  },
  {
    image: './Images/Project13.png',
    title: 'Instagram Post',
    description: 'CANVA',
    liveLink: 'https://www.canva.com/design/DAF_j-dyISY/TnUCib8Q5oyjv5n-Ms8f1g/edit?utm_content=DAF_j-dyISY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton',
  },
  {
    image: './Images/Project12.png',
    title: 'Instagram Post',
    description: 'CANVA',
    liveLink: 'https://www.canva.com/design/DAF8F-cjF_E/JqAHjeUnl9qXmTu5fQTI7w/edit?utm_content=DAF8F-cjF_E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton',
  },
  {
    image: './Images/Project14.png',
    title: 'Card',
    description: 'CANVA',
    liveLink: 'https://www.canva.com/design/DAGTeF99YP0/On8JRaREtQybWPNIm7Z1Dg/edit?utm_content=DAGTeF99YP0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton',
  },
  {
    image: './Images/Project15.png',
    title: 'SIH Prototype',
    description: 'CANVA',
    liveLink: 'https://wlug.my.canva.site/sih-prototype',
  },
  {
    image: './Images/Project7.png',
    title: 'Homepage UI',
    description: 'FIGMA',
    liveLink: 'https://www.figma.com/design/Qren86AeaiagA7obgZeYKg/NIKE?node-id=0-1&t=wd77e3XOnw6vm9lm-1',
  },
  {
    image: './Images/Project6.png',
    title: 'Game UI',
    description: 'FIGMA',
    liveLink: 'https://www.figma.com/design/gH5dDKTsCempHaxr10Svhx/Game-UI?node-id=0-1&t=aIrdKZxV7Lfgd3w0-1',
  },
  {
    image: './Images/Project16.png',
    title: '3D Element',
    description: 'FIGMA',
    liveLink: 'https://www.figma.com/design/CihCCfQKdgcRSGUHMSUvzL/3D-Element?node-id=0-1&m=dev&t=zECe1Z4G5w1jr3yM-1',
  },
  {
    image: './Images/Project17.png',
    title: 'Glass Element',
    description: 'FIGMA',
    liveLink: 'https://www.figma.com/design/YIBYbGgPD3lwneyKIQN3MA/Glass-Element?node-id=2-3&m=dev&t=5T1dqdBM6ZjmmNFA-1',
  },
  {
    image: './Images/Project1.png',
    title: 'WCE Login',
    description: 'HTML CSS',
    githubLink: 'https://github.com/Ashutoshbirje/WCE_Login.git',
    liveLink: 'https://ashutoshbirje.github.io/WCE_Login/',
  },
  {
    image: './Images/Project2.png',
    title: 'Dice Game',
    description: 'HTML CSS JS',
    githubLink: 'https://github.com/Ashutoshbirje/Dice-Game.git',
    liveLink: 'https://ashutoshbirje.github.io/Dice-Game/',
  },
  {
    image: './Images/Project3.jpeg',
    title: 'Portfolio',
    description: 'HTML CSS JS',
    githubLink: 'https://github.com/Ashutoshbirje/Portfoilo.git',
    liveLink: 'https://ashutoshbirje.github.io/Portfoilo/',
  },
  {
    image: './Images/Project4.png',
    title: 'Drum Kit',
    description: 'HTML CSS JS',
    githubLink: 'https://github.com/Ashutoshbirje/Drum-Kit.git',
    liveLink: 'https://ashutoshbirje.github.io/Drum-Kit/',
  },
  {
    image: './Images/Project5.png',
    title: 'Calculator',
    description: 'HTML CSS JS',
    githubLink: 'https://github.com/Ashutoshbirje/Calculater.git',
    liveLink: 'https://ashutoshbirje.github.io/Calculater/',
  },
  {
    image: './Images/Project8.png',
    title: 'Crick_App',
    description: 'REACT',
    githubLink: 'https://github.com/Ashutoshbirje/Crick_App.git',
    liveLink: 'https://vplcrick.netlify.app/',
  },
];
